### ISSUE TITLE
Crash on connection close using blpop

### ISSUE THREAD

**Issue by oliwer** [marcusramberg/mojo-redis#31]
Hi,

Here is a small worker program that consume items on a Redis queue using blpop.

```
#!/usr/bin/env perl

use Mojo::Base -strict;
use Mojo::Redis;

my $redis = Mojo::Redis->new;

$redis->on(blpop => 'test', sub {
    my ($redis, $err, $msg, $chan) = @_;
    warn $err if $err;
    say $msg;
});

$redis->ioloop->start;
```

When I start this program  and stop redis-server, it dies with the following error:
   Can't use an undefined value as an ARRAY reference at /usr/local/share/perl/5.18.2/Mojo/Redis.pm line 407.
    Use of uninitialized value $msg in say at ./simple.pl line 11.

Btw, I had the same error in a Mojo::Lite application when I was using blpop outside of a Mojo::IOLoop->delay and stopping it with ctrl+c.

It seems empty blpop events are emitted on connection close.

**Comment by jhthorsen** [comment]
Why did you close this @oliwer?

**Comment by oliwer** [comment]
I was just cleaning up my list of open issues on github. It's not like this issue is gonna get fixed, is it? :smile:

**Comment by jhthorsen** [comment]
I'm pretty sure it will be fixed, I just don't have the time to do it now.

(I don't think it should be too hard to fix though)

**Comment by oliwer** [comment]
I thought this module was abandoned is favor of mojo-redis2 ?

**Comment by jhthorsen** [comment]
Ah! That explains why I didn’t remember you opening this ticket: I thought we were in https://github.com/jhthorsen/mojo-redis 🙈

(Also, it was obvious once I read your code example)
